name: Tennis Court Booking

on:
  schedule:
    # Run at 1:26 AM Central Time for testing
    - cron: "26 6 * * *" # For CDT (UTC-5)
    # - cron: "26 7 * * *"  # For CST (UTC-6)
  workflow_dispatch: # Allow manual triggering

jobs:
  book-court:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          fetch-depth: 0 # Fetch all history for push
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"

      # Make a small change to force a commit
      - name: Update timestamp file
        run: |
          echo "Last run: $(date)" > timestamp.txt
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add timestamp.txt
          git commit -m "Update timestamp [skip ci]" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager pytz

      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run booking script
        env:
          COURTRESERVE_EMAIL: ${{ secrets.COURTRESERVE_EMAIL }}
          COURTRESERVE_PASSWORD: ${{ secrets.COURTRESERVE_PASSWORD }}
        run: |
          python book.py

      - name: List debug files
        if: always()
        run: |
          echo "PNG files:"
          ls -la *.png || echo "No PNG files found"
          echo "HTML files:"
          ls -la *.html || echo "No HTML files found"
